[toolchain]
channel = "1.74.0"
components = ["rust-analyzer"]
profile = "default"

# For static linking for deployment.
# `RUSTFLAGS="-C target-feature=+crt-static" cargo build --target=x86_64-unknown-linux-musl`
targets = ["x86_64-unknown-linux-musl"]
